import './globals.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import { DataProvider } from './DataProvider';
import ScrollProgress from '@/components/ui/ScrollProgress';

export const metadata = {
	title: 'Al-Huda',
	description: 'Generated by create next app',
	icons: {
		icon: '/logos/logo2.png',
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<ScrollProgress />
				<DataProvider>{children}</DataProvider>
				<Footer />
			</body>
		</html>
	);
}
